WPNRPM = 480
GUNCOOLDOWN = 1/(WPNRPM/60)
PEER_TIMEOUT = 5

PLAYER_SPEED = 100
PLAYER_SPRINT_MULT = 2.25
PLAYER_MAX_STAMINA = 500
PLAYER_STAMINA_COOLDOWN = 1.5

BULLET_SPEED = 1280*4
BULLET_DMG = 12
MAX_BULLETS = 6
HEADSHOT_DMG_MULTIPLIER = 2.5

BLOOD_PARTICLE_LIFETIME = 0.2
BLOOD_PARTICLE_SPEED = 16
BLOOD_PARTICLE_COUNT = 500
MAX_BLOOD_PARTICLES = 6500

RELOAD_TIME_SECS = 1.5

WIDTH = 600
HEIGHT = 600

MOTION_BLUR = False
MAX_BLUR_FRAMES = 1

POSITIONUPDATEINTERVAL = 1/20

POSITION_UPDATE_PACKET_IN_MAIN_LOOP = False